Tic tac toe game
JozefR/ReactLearn pull request #1
Opened 2022-07-02 13:04 UTC by JozefR

Be kind !

2022-07-02 14:07 UTC, juliavorcakova requested changes
You rocked that!

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +    const xIsNext = !this.state.xIsNext;
I don't understand.. why falsy? In my understanding xIsNext should be just xIsNext = this.state.xIsNext;
Also you dont need to assing it to new const you can just use directly this.state.xIsNext;

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +    const xIsNext = !this.state.xIsNext;
Ahhh I understand now - you want to toggle it right?

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +      squares: squares,
Just so you know, easier syntax is just {squares, swaureHistory...} - if the key is named the same as the value ocnst u can use just the above syntax.

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +  var historyElements = historyOptions.map((element) => {
You don't have to handle the index separately - map has index as a second argument so u can just do (element, index) => ...
Also try not to use 'var' and just return it directly, you dont have to assign it to const and then return it ;)

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +    buttonText += "Go to game start";
why += just =

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +    return <Square value={value} onClick={props.onClick} />;
To simplify it you can just do `return <Square value={value || ''} onClick={props.onClick} />`. The || takes the first value if it's not falsy othervise it takes the second one. Or if you dont like it just fo `return <Square value={value !== null ? value : ''} onClick={props.onClick} />;`

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +function RenderSquare(props) {
I dont understand why u have this as a separate component - you should avoid having component which just perform some action. Think of component as UI units (you can really see them in UI). The same for others 'Render...' components.

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +        <RenderSquare
Just call directly <Square> component, why the abstraction

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +function RenderSquareHistory(props) {
Same as below. This component is not necesary. If you need to perform some conditions and you don't want to do it directly at the html (jsx) code then just create a function in <Board> component, but not a new component just to render another component.

2022-07-02 14:07 UTC, juliavorcakova commented on my-app/src/index1.js
> +    <button className="square" onClick={props.onClick}>
Wait so at the end you are not sending the index as a param of the onclick. So where is the index param in <Game> compoent 'handleClick' fn coming from?

2022-07-03 12:13 UTC, JozefR commented on my-app/src/index1.js
> +    const xIsNext = !this.state.xIsNext;
Yes it's toggled every time user clicks the square button.

2022-07-03 12:17 UTC, JozefR commented on my-app/src/index1.js
> +      squares: squares,
Thanks, i will fix it.

2022-07-03 13:02 UTC, merged